### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by ieea** [audioku/cross-accent-maml-asr#3]
Hi,
Thanks for the support.
I am trying to execute the command "python meta_train.py" but i am getting following error. Please help !!

**_Error: pop from empty list, fetching new data...
Exception in thread Thread-58:
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ubuntu/ca_speaker/cross-accent-maml-asr/trainer/asr/meta_trainer.py", line 128, in fetch_train_batch
    batch_data = train_data_list[manifest_id].sample(k_train, k_valid, manifest_id)
  File "/home/ubuntu/ca_speaker/cross-accent-maml-asr/utils/data_loader.py", line 274, in sample
    spect = self.parse_audio(audio_path)[:,:self.args.src_max_len]
  File "/home/ubuntu/ca_speaker/cross-accent-maml-asr/utils/data_loader.py", line 69, in parse_audio
    y = load_audio(audio_path)
  File "/home/ubuntu/ca_speaker/cross-accent-maml-asr/utils/audio.py", line 8, in load_audio
    sound, _ = torchaudio.load(path, normalization=True)
TypeError: load() got an unexpected keyword argument 'normalization'_**

**Comment by SamuelCahyawijaya** [comment]
I think you probably use a different version of `torchaudio`. I am not sure what the exact version is since the environment is long gone. Hope it helps!
